name: Scheduled Message
on:
  schedule:
    - cron: '20 18 * * 1-5' # 14:56 BRT = 17:56 UTC
  workflow_dispatch:

jobs:
  send-message:
    runs-on: ubuntu-latest
    steps:
      - name: Send message to Teams
        run: |
          curl -X POST https://bot-mensagem-juridica-node-beige.vercel.app/send-message \
               -H "Content-Type: application/json"
